#!/usr/bin/env python
import cv2
import numpy as np
import rospy
from sensor_msgs.msg import Image
from geometry_msgs.msg import Twist
from std_msgs.msg import Float32
from cv_bridge import CvBridge, CvBridgeError
from std_msgs.msg import Empty       	 # for land/takeoff/emergency
import sys
import threading
import time

#originally a copy of Mr. Batra's drone_detector program

class Detector:
    YELLOW = [np.array(x, np.uint8) for x in [[25,100,100], [35, 255, 255]] ]
    MAX_DETECTIONS = 1
    ERODE = (5,5)
    

    def get_filtered_contours(self,img):
        hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        
        hsv_img = cv2.erode(hsv_img, self.ERODE, iterations=10)  #XXX
        frame_threshed = cv2.inRange(hsv_img, self.YELLOW[0], self.YELLOW[1])
        ret,thresh = cv2.threshold(frame_threshed, self.YELLOW[0][0], 255, 0)
         

        filtered_contours = []
        contours, hierarchy = cv2.findContours(\
                thresh,cv2.RETR_CCOMP,cv2.CHAIN_APPROX_SIMPLE)
        contour_area = [ (cv2.contourArea(c), (c) ) for c in contours]
        contour_area = sorted(contour_area,reverse=True, key=lambda x: x[0])

        height,width = img.shape[:2]
        for j, (area,(cnt)) in enumerate(contour_area):
            if j > self.MAX_DETECTIONS: continue
            x,y,w,h = cv2.boundingRect(cnt)
            box = (x,y,w,h)
            d =  0.5*(x-width/2)**2 + (y-height)**2 
            if d < 20000: continue # filter tiny

            mask = np.zeros(thresh.shape,np.uint8)
            cv2.drawContours(mask,[cnt],0,255,-1)
            mean_val = cv2.mean(img,mask = mask)
            aspect_ratio = float(w)/h
            filtered_contours.append( (cnt, box, d, aspect_ratio, mean_val) )
            #print filtered_contours
        return filtered_contours


    def contour_match(self, img):
        '''
        Returns 1. Image with bounding boxes added
                2. an ObstacleImageDetectionList
        '''

        height,width = img.shape[:2]
        cx, cy = (-1,-1)
        # get filtered contours
        contours = self.get_filtered_contours(img)
        j = 0
        for (cnt, box, ds, aspect_ratio, mean_color)  in contours:
            j += 1            
            # plot box and label around contour
            x,y,w,h = box
            font = cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(img,"yellow", (x,y), font, 1,mean_color,4)
            cv2.rectangle(img,(x,y),(x+w,y+h), mean_color,2)
            if j == 1:
              cx = float(x + w/2)/width
              cy = float(y + h/2)/height

        return img, cx, cy

class StaticObjectDetectorNode:
    def __init__(self):
        self.name = 'static_object_detector_node'
        
        self.detector = Detector()
        self.thread_lock = threading.Lock()
        self.sub_image = rospy.Subscriber("/ardrone/image_raw", Image, self.cbImage, queue_size=1)
        self.pub_image = rospy.Publisher("~detection_image", Image, queue_size=1)
        #self.pub_twist = rospy.Publisher('/ardrone/cmd_vel', Twist, queue_size = 1)
        self.pub_twist = rospy.Publisher('cmd_vel', Twist, queue_size = 1)
        
        self.bridge = CvBridge()
        rospy.loginfo("[%s] Initialized." %(self.name))
        self.takeoff = rospy.Publisher('/takeoff',Empty)
        self.takeoff.publish(Empty)

    def cbImage(self,image_msg):
        thread = threading.Thread(target=self.processImage,args=(image_msg,))
        thread.setDaemon(True)
        thread.start()

    def processImage(self, image_msg):
        if not self.thread_lock.acquire(False):
            return
        try:
            image_cv=self.bridge.imgmsg_to_cv2(image_msg,"bgr8")
        except CvBridgeErrer as e:
            print e
        img, cx, cy = self.detector.contour_match(image_cv)

        twist = Twist()
        speed = 0.0 ## 0.5
        turn = 1.0
        x,y,z,th = (0,0,0,0)
        if cx > 0.55:
           th = -1
        elif cx < 0.45:
           th = 1

        twist.linear.x = x*speed; twist.linear.y = y*speed; twist.linear.z = z*speed;
	twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = th*turn
	self.pub_twist.publish(twist)            

        height,width = img.shape[:2]
        print "center x: " + str(cx) + " center y: " + str(cy)
        #print "height: " + str(height)+"  width: " + str(width)
        try:
            self.pub_image.publish(self.bridge.cv2_to_imgmsg(img, "bgr8"))
        except CvBridgeError as e:
            print(e)

        self.thread_lock.release()

if __name__=="__main__":
	rospy.init_node('static_object_detector_node')
        #time.sleep(3)
        
	node = StaticObjectDetectorNode()
	rospy.spin()
